-- ---------------------------------------------------------------------------
-- E-Masterclass Big Five — jeu de données initial
--
-- FICHIER GÉNÉRÉ : ne pas éditer à la main.
-- Régénération : npm run db:sql
--
-- À exécuter en dernier, sur une base neuve uniquement : le contenu
-- éditorial (18 modules et leurs chapitres, fiches formateurs, articles),
-- les comptes de démonstration et les réglages du back-office.
--
-- Sur une base qui contient déjà ces données, ce fichier échouerait sur les
-- clés primaires — c'est voulu, il ne doit pas écraser du contenu existant.
--
-- Source : server/data/db.ts — régénérer avec `npm run db:seed:generer`.
-- ---------------------------------------------------------------------------

-- Programmes
insert into programmes (id, slug, nom, surtitre_hero, h1_variable, description_hero, cta_hero, description_programme, description_carte, couleur, seo_mot_cle_principal, seo_title, seo_meta_description, seo_og_title, seo_og_description, seo_og_image, seo_canonical, seo_indexable) values
  ('prg-social-media', 'social-media', 'Social Média', 'Programme Social Média', 'Restez dans la course.', 'Choisissez parmi 9 modules de 60 minutes pour renforcer des compétences précises en stratégie, contenu et plateformes Social Media. Accès à vie et sessions de coaching collectif.', 'Découvrir le programme Social Média', 'Des modules indépendants conçus pour les Social Media Managers, Community Managers et professionnels de la communication qui souhaitent actualiser leurs pratiques et renforcer des compétences ciblées.', 'Pour les professionnels du Social Media et de la communication qui souhaitent actualiser leurs pratiques et renforcer des compétences précises.', '#80368D', 'formation social média Abidjan', 'Programme Social Média | E-Masterclass Big Five', 'Neuf modules de 60 minutes pour renforcer des compétences précises en stratégie, contenu et plateformes Social Media. 10 000 FCFA TTC par module, accès à vie.', null, null, null, null, true),
  ('prg-entrepreneurs', 'entrepreneurs', 'Entrepreneurs', 'Programme Entrepreneurs', 'Soyez à jour.', 'Choisissez parmi 9 modules de 60 minutes pour renforcer les compétences utiles au développement de votre activité : valider une idée, fixer vos prix, vendre et gagner en visibilité.', 'Découvrir le programme Entrepreneurs', 'Des modules indépendants conçus pour les entrepreneurs en activité ou en lancement qui souhaitent renforcer des compétences pratiques et faire évoluer leur activité.', 'Pour les entrepreneurs en activité ou en lancement qui souhaitent renforcer les compétences utiles au développement de leur activité.', '#29358B', 'formation entrepreneur Côte d’Ivoire', 'Programme Entrepreneurs | E-Masterclass Big Five', 'Neuf modules de 60 minutes pour valider une idée, fixer ses prix, vendre et gagner en visibilité. 10 000 FCFA TTC par module, accès à vie.', null, null, null, null, true);

-- Thématiques — sections des pages programme
insert into thematiques (id, numero, nom, programme) values
  ('th-sm-fondations', 1, 'Fondations stratégiques', 'social-media'),
  ('th-sm-copywriting', 2, 'Copywriting & contenu', 'social-media'),
  ('th-sm-plateformes', 3, 'Plateformes', 'social-media'),
  ('th-ent-fondations', 1, 'Fondations du business', 'entrepreneurs'),
  ('th-ent-vente', 2, 'Vente & acquisition', 'entrepreneurs'),
  ('th-ent-visibilite', 3, 'Visibilité', 'entrepreneurs');

-- Formateurs
insert into formateurs (id, slug, nom, expertise, bio, programme_principal, photo, fiche_complete, coaching_prive_fcfa_heure, coaching_prive_actif, seo_mot_cle_principal, seo_title, seo_meta_description, seo_og_title, seo_og_description, seo_og_image, seo_canonical, seo_indexable) values
  ('for-declercq', 'jeremie-de-clercq', 'Jérémie De Clercq', 'Stratégie business & entrepreneuriat', 'Jérémie De Clercq intervient sur les modules consacrés à la structuration des fondamentaux d’une activité : modèle économique, coûts, prix et lecture du marché. Il accompagne des entrepreneurs et des équipes marketing en Afrique francophone.', 'entrepreneurs', '/images/formateurs/jeremie-de-clercq.svg', true, 50000, false, null, null, null, null, null, null, null, true),
  ('for-othniel', 'coury-othniel', 'Coury Othniel', 'Copywriting & contenu', 'Copywriter spécialisé dans les contenus qui retiennent l’attention sur les réseaux sociaux en Afrique francophone. Il anime les modules de rédaction persuasive des deux programmes.', 'social-media', '/images/formateurs/coury-othniel.svg', true, 50000, true, null, null, null, null, null, null, null, true),
  ('for-waffo', 'kevine-waffo', 'Kevine Waffo', 'Stratégie social media & ciblage', 'Kevine Waffo construit des plans d’action social media pour des marques et des institutions : diagnostic, ciblage, planning éditorial et pilotage des publications.', 'social-media', '/images/formateurs/kevine-waffo.svg', true, 50000, true, null, null, null, null, null, null, null, true),
  ('for-cocou', 'emmanuel-cocou', 'Emmanuel Cocou', 'Offres & positionnement', 'Emmanuel Cocou aide les entrepreneurs à transformer une compétence en offre lisible : périmètre, promesse, livrables et argumentaire de vente.', 'entrepreneurs', '/images/formateurs/emmanuel-cocou.svg', true, 50000, false, null, null, null, null, null, null, null, true),
  ('for-nontondji', 'maurice-nontondji', 'Maurice Nontondji', 'LinkedIn : algorithme & prospection', 'Maurice Nontondji travaille la visibilité professionnelle sur LinkedIn : compréhension de l’algorithme, formats de publication et prospection directe.', 'social-media', '/images/formateurs/maurice-nontondji.svg', true, 50000, false, null, null, null, null, null, null, null, true),
  ('for-soboro', 'lyle-soboro', 'Lyle Soboro', 'Vente, TikTok & acquisition client', 'Lyle Soboro accompagne des vendeurs et des commerces dans l’acquisition client sans site web : WhatsApp Business, TikTok et tunnels de vente simples.', 'entrepreneurs', '/images/formateurs/lyle-soboro.svg', true, 50000, true, null, null, null, null, null, null, null, true),
  ('for-akinocho', 'nouroudine-akinocho', 'Nouroudine Akinocho', 'Visibilité & croissance en ligne', 'Nouroudine Akinocho intervient sur la visibilité en ligne des petites structures : référencement local, présence sur les plateformes et croissance organique.', 'entrepreneurs', '/images/formateurs/nouroudine-akinocho.svg', true, 50000, false, null, null, null, null, null, null, null, true);

-- Modules — 9 par programme
insert into modules (id, slug, numero, titre, programme, thematique_id, formateur_id, promesse, pourquoi, pour_qui, prerequis, acquis, livrable, faq, duree_minutes, prix_fcfa, statut, publie_le, seo_mot_cle_principal, seo_title, seo_meta_description, seo_og_title, seo_og_description, seo_og_image, seo_canonical, seo_indexable) values
  ('mod-comprendre-le-business-du-client', 'comprendre-le-business-du-client', 1, 'Comprendre le business du client', 'social-media', 'th-sm-fondations', 'for-declercq', 'Apprenez à lire l’activité d’une marque avant de produire le moindre contenu, pour proposer une stratégie qui sert ses objectifs.', 'Un contenu peut être soigné et régulier sans rien apporter à l’entreprise qui le publie. Ce module vous donne la grille de lecture qui permet de comprendre un modèle économique, ses marges et ses priorités, puis d’en déduire ce que le social media doit réellement produire.', array['Vous gérez les réseaux sociaux d’une marque ou de plusieurs clients.', 'Vos recommandations sont difficiles à défendre en réunion.', 'Vous souhaitez relier vos contenus aux objectifs commerciaux.']::text[], 'Aucun prérequis particulier.', array['analyser le modèle économique d’une marque ;', 'identifier ses priorités commerciales ;', 'formuler des objectifs social media alignés.']::text[], 'Une fiche de cadrage client réutilisable pour chaque nouvelle marque ou chaque nouveau projet.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-plan-daction-social-media-strategie-et-ciblage', 'plan-daction-social-media-strategie-et-ciblage', 2, 'Plan d’action social media : Stratégie & Ciblage', 'social-media', 'th-sm-fondations', 'for-waffo', 'Construisez un plan d’action social media qui part d’une cible précise plutôt que d’une intuition.', 'Publier pour « tout le monde » revient à ne parler à personne. Ce module structure le diagnostic, le choix de la cible et les axes stratégiques qui en découlent, avec des arbitrages assumés.', array['Vous démarrez sur un nouveau compte ou une nouvelle marque.', 'Vos publications touchent une audience trop large ou mal qualifiée.', 'Vous devez présenter une stratégie à un décideur.']::text[], 'Aucun prérequis particulier.', array['poser un diagnostic factuel ;', 'définir une cible exploitable ;', 'construire un plan d’action argumenté.']::text[], 'Un plan d’action social media sur une page, prêt à être présenté.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-plan-daction-social-media-planning-editorial', 'plan-daction-social-media-planning-editorial', 3, 'Plan d’action social media : Planning éditorial', 'social-media', 'th-sm-fondations', 'for-waffo', 'Transformez une stratégie en planning tenable, avec des formats et un rythme que vous pourrez réellement soutenir.', 'La régularité échoue rarement par manque d’idées : elle échoue par manque de système. Ce module installe un planning éditorial calibré sur vos moyens réels de production.', array['Vous publiez de façon irrégulière.', 'Vous manquez d’idées en fin de mois.', 'Vous travaillez seul ou avec une petite équipe.']::text[], 'Avoir défini une cible et des axes stratégiques.', array['construire un planning éditorial mensuel ;', 'choisir des formats adaptés à ses moyens ;', 'anticiper la production de contenu.']::text[], 'Un planning éditorial mensuel complété et une banque d’idées de départ.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-formules-de-redaction-persuasive', 'formules-de-redaction-persuasive', 4, 'Formules de rédaction persuasive', 'social-media', 'th-sm-copywriting', 'for-othniel', 'Appliquez des structures de rédaction éprouvées pour écrire plus vite des messages qui portent.', 'Devant une page blanche, la qualité dépend du temps disponible. Les formules de rédaction suppriment cette dépendance : elles donnent une ossature au message et libèrent l’attention pour le fond.', array['Vous écrivez régulièrement pour les réseaux sociaux.', 'Vos textes manquent de structure ou de chute.', 'Vous voulez réduire votre temps de rédaction.']::text[], 'Aucun prérequis particulier.', array['utiliser plusieurs structures de rédaction ;', 'adapter une formule à son contexte ;', 'réécrire un texte de façon méthodique.']::text[], 'Un carnet de formules annotées et adaptées à votre activité.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 'accroches-qui-stoppent-le-scroll-et-ia-copywriting', 5, 'Accroches qui stoppent le scroll & IA copywriting', 'social-media', 'th-sm-copywriting', 'for-othniel', 'Apprenez à construire plus rapidement des accroches capables de retenir l’attention, avec une méthode claire et l’IA comme assistant.', 'Une publication peut être utile, bien conçue et correctement ciblée sans retenir l’attention si son ouverture manque d’impact. Ce module vous aide à structurer vos premiers mots, varier vos angles et produire plus rapidement sans déléguer votre réflexion à l’IA.', array['Vous gérez les réseaux sociaux d’une marque ou de plusieurs clients.', 'Vos contenus peinent à retenir l’attention.', 'Vous souhaitez produire plus rapidement sans sacrifier la qualité.']::text[], 'Aucun prérequis particulier. La méthode est expliquée et appliquée progressivement pendant le module.', array['reconnaître les éléments qui rendent une accroche plus efficace ;', 'produire plusieurs propositions rapidement ;', 'utiliser l’IA pour enrichir la réflexion et varier les angles.']::text[], 'Une bibliothèque personnelle de 30 accroches adaptées à votre secteur, accompagnée d’une routine de travail pour produire plus rapidement de nouvelles propositions avec l’aide de l’IA.', '[{"question":"Ai-je besoin d’un outil d’IA payant ?","reponse":"Non. Le module ne dépend pas d’un outil payant particulier. Les fonctionnalités nécessaires et les différentes options sont présentées pendant le module."},{"question":"La méthode peut-elle s’appliquer à tous les secteurs ?","reponse":"Oui. Les principes enseignés sont adaptables à différents secteurs. Les exercices vous permettent de travailler directement à partir de votre activité, de votre marque ou de vos clients."},{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-creer-un-buzz-sur-les-reseaux-sociaux', 'creer-un-buzz-sur-les-reseaux-sociaux', 6, 'Créer un buzz sur les réseaux sociaux', 'social-media', 'th-sm-copywriting', 'for-othniel', 'Comprenez ce qui déclenche réellement la circulation d’un contenu, et ce qu’il est raisonnable d’en attendre.', 'Le buzz n’est pas un objectif de communication : c’est une conséquence. Ce module démonte les mécaniques de diffusion et distingue ce qui se pilote de ce qui relève du hasard.', array['Vous travaillez sur une marque grand public.', 'On vous demande régulièrement « du viral ».', 'Vous souhaitez arbitrer entre visibilité et réputation.']::text[], 'Aucun prérequis particulier.', array['identifier les ressorts de diffusion ;', 'concevoir un contenu partageable ;', 'anticiper les risques de réputation.']::text[], 'Une grille d’évaluation des risques et opportunités avant publication.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'en-preparation', null, null, null, null, null, null, null, null, false),
  ('mod-linkedin-algorithme-et-prospection', 'linkedin-algorithme-et-prospection', 7, 'LinkedIn : algorithme & prospection', 'social-media', 'th-sm-plateformes', 'for-nontondji', 'Utilisez LinkedIn comme un canal de prospection, pas seulement comme une vitrine professionnelle.', 'LinkedIn récompense des comportements précis. Ce module explique ce que la plateforme valorise, puis construit une routine de publication et de prise de contact qui tient en trente minutes par jour.', array['Vous vendez à des professionnels.', 'Votre profil reçoit peu de visites.', 'Vos prises de contact restent sans réponse.']::text[], 'Disposer d’un profil LinkedIn actif.', array['optimiser son profil ;', 'publier des formats adaptés ;', 'structurer une séquence de prise de contact.']::text[], 'Une séquence de prospection en cinq messages, prête à personnaliser.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-instagram-formats-et-croissance', 'instagram-formats-et-croissance', 8, 'Instagram : formats et croissance', 'social-media', 'th-sm-plateformes', 'for-nontondji', 'Choisissez les formats Instagram qui font réellement progresser un compte, et abandonnez les autres.', 'Chaque format Instagram sert un objectif différent. Ce module cartographie les formats disponibles, leur coût de production et leur effet mesuré sur la croissance.', array['Vous animez un compte Instagram professionnel.', 'Votre croissance stagne malgré la régularité.', 'Vous hésitez entre les formats.']::text[], 'Disposer d’un compte professionnel Instagram.', array['choisir un format selon son objectif ;', 'produire un format court au téléphone ;', 'lire les statistiques de son compte.']::text[], 'Un plan de production hebdomadaire calibré sur vos moyens.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-publicite-sociale-lancer-sa-premiere-campagne', 'publicite-sociale-lancer-sa-premiere-campagne', 9, 'Publicité sociale : lancer sa première campagne', 'social-media', 'th-sm-plateformes', 'for-soboro', 'Lancez une première campagne payante maîtrisée, avec un budget contenu et un résultat mesurable.', 'La publicité sociale amplifie ce qui fonctionne déjà et gaspille tout le reste. Ce module suit une campagne réelle du cadrage jusqu’à la lecture des résultats.', array['Vous n’avez jamais lancé de campagne payante.', 'Vos précédentes campagnes n’ont pas été mesurées.', 'Vous disposez d’un budget limité.']::text[], 'Disposer d’une page professionnelle active.', array['paramétrer une campagne complète ;', 'construire une audience pertinente ;', 'interpréter un rapport de performance.']::text[], 'Un modèle de brief de campagne et une grille de lecture des résultats.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-valider-son-idee-de-business-avant-dinvestir', 'valider-son-idee-de-business-avant-dinvestir', 1, 'Valider son idée de business avant d’investir', 'entrepreneurs', 'th-ent-fondations', 'for-declercq', 'Vérifiez qu’une idée répond à un besoin réel avant d’y engager du temps et de l’argent.', 'La majorité des projets échouent sur une hypothèse jamais vérifiée. Ce module transforme une intuition en série de tests simples, réalisables en quelques jours et sans budget.', array['Vous avez une idée que vous n’avez pas encore testée.', 'Vous hésitez à investir dans un premier stock ou un outil.', 'Vous voulez éviter de construire ce que personne n’achètera.']::text[], 'Aucun prérequis particulier.', array['formuler une hypothèse testable ;', 'concevoir un test rapide et peu coûteux ;', 'prendre une décision fondée sur des retours réels.']::text[], 'Un protocole de test complété, avec critères de décision définis à l’avance.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-fixer-le-juste-prix-de-ses-produits-et-services', 'fixer-le-juste-prix-de-ses-produits-et-services', 2, 'Fixer le juste prix de ses produits et services', 'entrepreneurs', 'th-ent-fondations', 'for-declercq', 'Apprenez à fixer un prix qui couvre vos coûts, valorise votre travail et reste cohérent avec votre marché.', 'Un prix trop faible fragilise votre marge, tandis qu’un prix mal aligné avec le marché peut freiner la vente. Ce module vous aide à sortir des décisions prises uniquement au feeling pour construire et défendre un prix fondé sur des éléments concrets.', array['Vous lancez ou gérez votre activité.', 'Vous ne connaissez pas précisément votre coût de revient.', 'Vous diminuez vos prix dès qu’un client négocie.', 'Vous souhaitez mieux défendre la valeur de votre offre.']::text[], 'Aucun prérequis particulier. Prévoyez simplement les informations disponibles sur vos coûts, vos charges et vos prix actuels.', array['calculer son coût de revient ;', 'choisir une stratégie de prix ;', 'présenter et défendre son prix avec davantage d’assurance.']::text[], 'Une grille tarifaire construite à partir des coûts réels et directement utilisable pour présenter ses prix aux clients.', '[{"question":"Dois-je déjà avoir lancé mon activité ?","reponse":"Non. Le module convient également aux porteurs de projet qui souhaitent construire leurs premiers prix sur des bases plus solides."},{"question":"Que faire si je ne connais pas encore tous mes coûts ?","reponse":"Le module vous aide à identifier les principales catégories à prendre en compte. Vous pourrez commencer avec les données disponibles, puis affiner progressivement vos calculs."},{"question":"La méthode fonctionne-t-elle pour les produits et les services ?","reponse":"Oui. Le module présente les éléments à considérer selon la nature de l’offre afin d’adapter le calcul et la stratégie de prix."},{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-structurer-une-offre-claire-qui-se-vend', 'structurer-une-offre-claire-qui-se-vend', 3, 'Structurer une offre claire qui se vend', 'entrepreneurs', 'th-ent-fondations', 'for-cocou', 'Passez d’une liste de compétences à une offre qu’un client comprend et peut acheter immédiatement.', 'Une offre floue se négocie toujours à la baisse. Ce module cadre le périmètre, le livrable, la promesse et le prix, puis construit l’argumentaire correspondant.', array['Vous proposez « un peu de tout ».', 'Vos devis donnent lieu à de longues discussions.', 'Vous souhaitez formaliser une offre reproductible.']::text[], 'Aucun prérequis particulier.', array['cadrer un périmètre ;', 'écrire une offre lisible ;', 'traiter les objections de prix.']::text[], 'Une fiche d’offre complète, prête à être envoyée à un prospect.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-trouver-ses-premiers-clients', 'trouver-ses-premiers-clients', 4, 'Trouver ses premiers clients', 'entrepreneurs', 'th-ent-vente', 'for-soboro', 'Mettez en place une routine de prospection simple qui produit des rendez-vous dès la première semaine.', 'Attendre que les clients viennent est la première cause d’arrêt d’activité. Ce module installe une méthode de prise de contact directe, adaptée aux réalités du marché local.', array['Vous démarrez votre activité.', 'Votre réseau proche est déjà épuisé.', 'La prospection vous met mal à l’aise.']::text[], 'Disposer d’une offre formulée.', array['constituer une liste de prospects ;', 'rédiger un message d’approche ;', 'suivre ses relances sans outil complexe.']::text[], 'Une liste de 50 prospects qualifiés et une séquence de messages prête à l’emploi.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-vendre-sans-site-web-whatsapp-business', 'vendre-sans-site-web-whatsapp-business', 5, 'Vendre sans site web : WhatsApp Business de A à Z', 'entrepreneurs', 'th-ent-vente', 'for-soboro', 'Transformez WhatsApp Business en véritable canal de vente, du catalogue jusqu’à la relance.', 'La majorité des ventes se concluent déjà sur WhatsApp, mais rarement de façon organisée. Ce module structure le catalogue, les réponses rapides, le suivi des commandes et les relances.', array['Vous vendez déjà via WhatsApp sans méthode.', 'Vous perdez des commandes dans le fil des conversations.', 'Vous n’avez pas de site et n’en voulez pas pour l’instant.']::text[], 'Disposer d’un numéro dédié à l’activité.', array['configurer WhatsApp Business ;', 'structurer une conversation de vente ;', 'organiser ses relances.']::text[], 'Un catalogue configuré et un jeu de réponses rapides adapté à votre activité.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-negocier-et-conclure-une-vente', 'negocier-et-conclure-une-vente', 6, 'Négocier et conclure une vente', 'entrepreneurs', 'th-ent-vente', 'for-cocou', 'Menez un entretien de vente jusqu’à la décision, sans céder systématiquement sur le prix.', 'Beaucoup d’entretiens se terminent par un « je vous rappelle ». Ce module donne une structure d’entretien et les formulations qui permettent de conclure ou d’obtenir un refus clair.', array['Vous vendez vous-même vos prestations.', 'Vos prospects reportent leur décision.', 'Vous acceptez trop souvent de baisser vos prix.']::text[], 'Avoir une offre et un prix définis.', array['conduire un entretien structuré ;', 'répondre aux objections courantes ;', 'obtenir une décision explicite.']::text[], 'Une trame d’entretien annotée et une liste d’objections avec leurs réponses.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-contenus-qui-attirent-des-clients', 'contenus-qui-attirent-des-clients', 7, 'Contenus qui attirent des clients', 'entrepreneurs', 'th-ent-visibilite', 'for-othniel', 'Produisez des contenus qui amènent des demandes entrantes plutôt que de simples félicitations.', 'Un contenu apprécié n’est pas un contenu qui vend. Ce module oriente la production vers les sujets qui déclenchent une prise de contact.', array['Vous publiez sans retombée commerciale.', 'Vous manquez de temps pour produire.', 'Vous voulez générer des demandes entrantes.']::text[], 'Aucun prérequis particulier.', array['choisir des sujets orientés demande ;', 'écrire un appel à la conversation ;', 'tenir un rythme de publication réaliste.']::text[], 'Une liste de 20 sujets à fort potentiel commercial pour votre activité.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-etre-visible-localement-sur-internet', 'etre-visible-localement-sur-internet', 8, 'Être visible localement sur internet', 'entrepreneurs', 'th-ent-visibilite', 'for-akinocho', 'Apparaissez dans les recherches locales de vos clients, sans budget publicitaire.', 'Une part importante des achats commence par une recherche locale. Ce module met en place les bases : fiche établissement, avis, cohérence des informations et présence sur les plateformes utiles.', array['Vous avez une activité avec une zone de chalandise.', 'Vos clients vous trouvent difficilement en ligne.', 'Vous n’avez pas de budget publicitaire.']::text[], 'Aucun prérequis particulier.', array['créer une fiche établissement complète ;', 'solliciter des avis clients ;', 'maintenir des informations cohérentes.']::text[], 'Une check-list de présence locale complétée pour votre activité.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true),
  ('mod-mesurer-ce-qui-fait-vraiment-avancer-son-activite', 'mesurer-ce-qui-fait-vraiment-avancer-son-activite', 9, 'Mesurer ce qui fait vraiment avancer son activité', 'entrepreneurs', 'th-ent-visibilite', 'for-akinocho', 'Suivez cinq indicateurs utiles plutôt que vingt tableaux que personne ne lit.', 'Sans mesure, chaque décision se prend au ressenti. Ce module sélectionne les indicateurs qui comptent réellement pour une petite structure et installe une routine de suivi hebdomadaire.', array['Vous ne savez pas quoi mesurer.', 'Vous accumulez des données sans les exploiter.', 'Vous voulez décider sur des faits.']::text[], 'Aucun prérequis particulier.', array['sélectionner ses indicateurs ;', 'construire un tableau de bord simple ;', 'installer une routine de revue.']::text[], 'Un tableau de bord d’une page, complété avec vos propres données.', '[{"question":"La session de coaching collectif est-elle comprise dans le prix ?","reponse":"Oui. L’achat donne accès aux sessions liées à la thématique du module, selon le calendrier et les places disponibles. Votre fiche apprenant devra être complétée avant votre participation."},{"question":"Puis-je revoir le module après l’avoir terminé ?","reponse":"Oui. Vous conservez un accès à vie au module depuis votre espace apprenant."}]'::jsonb, 60, 10000, 'disponible', '2026-06-01', null, null, null, null, null, null, null, true);

-- Chapitres — position 0 pour l’introduction
insert into chapitres (module_id, position, libelle, titre, duree_minutes, script, video_cle, video_duree_secondes) values
  ('mod-comprendre-le-business-du-client', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-comprendre-le-business-du-client', 1, 'Chapitre 1', 'Lire un modèle économique en quinze minutes', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : lire un modèle économique en quinze minutes."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-comprendre-le-business-du-client', 2, 'Chapitre 2', 'Identifier les priorités commerciales du client', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : identifier les priorités commerciales du client."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-comprendre-le-business-du-client', 3, 'Chapitre 3', 'Traduire ces priorités en objectifs social media', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : traduire ces priorités en objectifs social media."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-strategie-et-ciblage', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-strategie-et-ciblage', 1, 'Chapitre 1', 'Diagnostic : où en est réellement le compte', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : diagnostic : où en est réellement le compte."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-strategie-et-ciblage', 2, 'Chapitre 2', 'Définir une cible et ses points de friction', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : définir une cible et ses points de friction."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-strategie-et-ciblage', 3, 'Chapitre 3', 'Formuler trois axes stratégiques défendables', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : formuler trois axes stratégiques défendables."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-planning-editorial', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-planning-editorial', 1, 'Chapitre 1', 'Choisir ses piliers et ses formats', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : choisir ses piliers et ses formats."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-planning-editorial', 2, 'Chapitre 2', 'Calibrer un rythme soutenable', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : calibrer un rythme soutenable."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-plan-daction-social-media-planning-editorial', 3, 'Chapitre 3', 'Alimenter une banque d’idées qui se recharge', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : alimenter une banque d’idées qui se recharge."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-formules-de-redaction-persuasive', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-formules-de-redaction-persuasive', 1, 'Chapitre 1', 'Les structures de message qui fonctionnent', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : les structures de message qui fonctionnent."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-formules-de-redaction-persuasive', 2, 'Chapitre 2', 'Adapter une formule à son secteur', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : adapter une formule à son secteur."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-formules-de-redaction-persuasive', 3, 'Chapitre 3', 'Réécrire : le passage qui fait la différence', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : réécrire : le passage qui fait la différence."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, 'demo-accroches-ch01', 31),
  ('mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 1, 'Chapitre 1', 'Anatomie d’une accroche qui stoppe le scroll', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : anatomie d’une accroche qui stoppe le scroll."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, 'demo-accroches-ch02', 31),
  ('mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 2, 'Chapitre 2', 'Écrire 10 accroches en 15 minutes : la méthode', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : écrire 10 accroches en 15 minutes : la méthode."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 3, 'Chapitre 3', 'Utiliser l’IA comme assistant copywriting, pas comme remplaçant', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : utiliser l’ia comme assistant copywriting, pas comme remplaçant."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-creer-un-buzz-sur-les-reseaux-sociaux', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-creer-un-buzz-sur-les-reseaux-sociaux', 1, 'Chapitre 1', 'Ce qui fait circuler un contenu', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : ce qui fait circuler un contenu."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-creer-un-buzz-sur-les-reseaux-sociaux', 2, 'Chapitre 2', 'Concevoir un contenu conçu pour être partagé', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : concevoir un contenu conçu pour être partagé."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-creer-un-buzz-sur-les-reseaux-sociaux', 3, 'Chapitre 3', 'Gérer les retombées et les risques', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : gérer les retombées et les risques."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-linkedin-algorithme-et-prospection', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-linkedin-algorithme-et-prospection', 1, 'Chapitre 1', 'Ce que l’algorithme valorise réellement', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : ce que l’algorithme valorise réellement."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-linkedin-algorithme-et-prospection', 2, 'Chapitre 2', 'Un profil qui convertit les visites', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : un profil qui convertit les visites."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-linkedin-algorithme-et-prospection', 3, 'Chapitre 3', 'Une routine de prospection en trente minutes par jour', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : une routine de prospection en trente minutes par jour."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-instagram-formats-et-croissance', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-instagram-formats-et-croissance', 1, 'Chapitre 1', 'Cartographie des formats et de leur usage', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : cartographie des formats et de leur usage."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-instagram-formats-et-croissance', 2, 'Chapitre 2', 'Produire un format court efficace au téléphone', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : produire un format court efficace au téléphone."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-instagram-formats-et-croissance', 3, 'Chapitre 3', 'Lire ses statistiques et arbitrer', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : lire ses statistiques et arbitrer."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-publicite-sociale-lancer-sa-premiere-campagne', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-publicite-sociale-lancer-sa-premiere-campagne', 1, 'Chapitre 1', 'Choisir un objectif de campagne', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : choisir un objectif de campagne."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-publicite-sociale-lancer-sa-premiere-campagne', 2, 'Chapitre 2', 'Construire une audience et une créa', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : construire une audience et une créa."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-publicite-sociale-lancer-sa-premiere-campagne', 3, 'Chapitre 3', 'Lire un rapport et décider de la suite', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : lire un rapport et décider de la suite."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-valider-son-idee-de-business-avant-dinvestir', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-valider-son-idee-de-business-avant-dinvestir', 1, 'Chapitre 1', 'Formuler l’hypothèse à vérifier', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : formuler l’hypothèse à vérifier."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-valider-son-idee-de-business-avant-dinvestir', 2, 'Chapitre 2', 'Concevoir un test réalisable en une semaine', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : concevoir un test réalisable en une semaine."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-valider-son-idee-de-business-avant-dinvestir', 3, 'Chapitre 3', 'Décider : poursuivre, corriger ou abandonner', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : décider : poursuivre, corriger ou abandonner."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-fixer-le-juste-prix-de-ses-produits-et-services', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-fixer-le-juste-prix-de-ses-produits-et-services', 1, 'Chapitre 1', 'Calculer son coût de revient réel, charges comprises', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : calculer son coût de revient réel, charges comprises."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-fixer-le-juste-prix-de-ses-produits-et-services', 2, 'Chapitre 2', 'Comprendre les trois stratégies de prix et savoir quand les utiliser', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : comprendre les trois stratégies de prix et savoir quand les utiliser."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-fixer-le-juste-prix-de-ses-produits-et-services', 3, 'Chapitre 3', 'Annoncer et défendre son prix face au client', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : annoncer et défendre son prix face au client."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-structurer-une-offre-claire-qui-se-vend', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-structurer-une-offre-claire-qui-se-vend', 1, 'Chapitre 1', 'Délimiter un périmètre et un livrable', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : délimiter un périmètre et un livrable."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-structurer-une-offre-claire-qui-se-vend', 2, 'Chapitre 2', 'Écrire une promesse compréhensible en une phrase', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : écrire une promesse compréhensible en une phrase."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-structurer-une-offre-claire-qui-se-vend', 3, 'Chapitre 3', 'Construire l’argumentaire et traiter les objections', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : construire l’argumentaire et traiter les objections."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-trouver-ses-premiers-clients', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-trouver-ses-premiers-clients', 1, 'Chapitre 1', 'Constituer une liste de prospects qualifiés', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : constituer une liste de prospects qualifiés."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-trouver-ses-premiers-clients', 2, 'Chapitre 2', 'Écrire un premier message qui obtient une réponse', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : écrire un premier message qui obtient une réponse."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-trouver-ses-premiers-clients', 3, 'Chapitre 3', 'Tenir une routine de prospection quotidienne', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : tenir une routine de prospection quotidienne."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-vendre-sans-site-web-whatsapp-business', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-vendre-sans-site-web-whatsapp-business', 1, 'Chapitre 1', 'Configurer un compte professionnel et un catalogue', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : configurer un compte professionnel et un catalogue."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-vendre-sans-site-web-whatsapp-business', 2, 'Chapitre 2', 'Structurer la conversation de vente', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : structurer la conversation de vente."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-vendre-sans-site-web-whatsapp-business', 3, 'Chapitre 3', 'Relancer et fidéliser sans être intrusif', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : relancer et fidéliser sans être intrusif."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-negocier-et-conclure-une-vente', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-negocier-et-conclure-une-vente', 1, 'Chapitre 1', 'La structure d’un entretien de vente', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la structure d’un entretien de vente."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-negocier-et-conclure-une-vente', 2, 'Chapitre 2', 'Traiter les objections sans céder sur le prix', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : traiter les objections sans céder sur le prix."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-negocier-et-conclure-une-vente', 3, 'Chapitre 3', 'Conclure et sécuriser l’engagement', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : conclure et sécuriser l’engagement."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-contenus-qui-attirent-des-clients', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-contenus-qui-attirent-des-clients', 1, 'Chapitre 1', 'Identifier les sujets qui déclenchent un contact', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : identifier les sujets qui déclenchent un contact."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-contenus-qui-attirent-des-clients', 2, 'Chapitre 2', 'Écrire un contenu qui amène à la conversation', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : écrire un contenu qui amène à la conversation."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-contenus-qui-attirent-des-clients', 3, 'Chapitre 3', 'Installer un rythme tenable', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : installer un rythme tenable."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-etre-visible-localement-sur-internet', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-etre-visible-localement-sur-internet', 1, 'Chapitre 1', 'Créer et optimiser sa fiche établissement', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : créer et optimiser sa fiche établissement."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-etre-visible-localement-sur-internet', 2, 'Chapitre 2', 'Obtenir et gérer des avis clients', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : obtenir et gérer des avis clients."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-etre-visible-localement-sur-internet', 3, 'Chapitre 3', 'Assurer la cohérence de ses informations en ligne', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : assurer la cohérence de ses informations en ligne."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-mesurer-ce-qui-fait-vraiment-avancer-son-activite', 0, 'Introduction', 'Présentation du module et de votre formateur', 6, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : la présentation du module."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-mesurer-ce-qui-fait-vraiment-avancer-son-activite', 1, 'Chapitre 1', 'Choisir cinq indicateurs et écarter le reste', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : choisir cinq indicateurs et écarter le reste."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-mesurer-ce-qui-fait-vraiment-avancer-son-activite', 2, 'Chapitre 2', 'Construire un tableau de bord en une page', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : construire un tableau de bord en une page."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null),
  ('mod-mesurer-ce-qui-fait-vraiment-avancer-son-activite', 3, 'Chapitre 3', 'Tenir une revue hebdomadaire de quinze minutes', 18, '[{"temps":"00:12","texte":"Dans ce passage, nous posons le cadre : tenir une revue hebdomadaire de quinze minutes."},{"temps":"04:30","texte":"On déroule la méthode pas à pas, sur un cas réel."},{"temps":"09:05","texte":"Puis on met en pratique, avec vos propres données."}]'::jsonb, null, null);

-- Comptes de démonstration — mot de passe commun, voir README
insert into utilisateurs (id, prenom, nom, email, whatsapp, pays, role, fiche_completee, formateur_id, mot_de_passe_hache, sections_autorisees) values
  ('usr-aya', 'Aya', 'Koné', 'aya@example.ci', '+225 07 00 00 00 00', 'Côte d’Ivoire', 'apprenant', true, null, 'scrypt$16384$8$1$a22826f2045a3ce56c8ced828516748c$995728a7e90841bbe8088e4c5370161fc400a087f501bc95dd55bf2195f3010c03177023ed87f252ac4430ab80908d703ea2aa6378442c5cdc96ffe6933be92b', '{}'::section_admin[]),
  ('usr-moussa', 'Moussa', 'Diabaté', 'moussa@example.ci', '+225 05 00 00 00 00', 'Côte d’Ivoire', 'apprenant', true, null, 'scrypt$16384$8$1$b977e801947a3cda9dc6c5a707394ea6$040cac9c2794a5ccb2aa79b4285755262e4fc312da4f06af069d80a058c2a2a8a16796941713c0f1a265f0e2a8ff9fb8a30c562a0011f819bd7a4b7b64b7efc6', '{}'::section_admin[]),
  ('usr-fatou', 'Fatou', 'Bamba', 'fatou@example.bj', '+229 96 00 00 00', 'Bénin', 'apprenant', false, null, 'scrypt$16384$8$1$8472433c6d1c39bc03ad355160dbfa86$90a4ff26b70745b2c3aa8a7e208f234742da8712fa8d8909f4e55d0ab56538f5f5d0f12450ec80c3160724de1a325e05ba734753093435a0214c069423122894', '{}'::section_admin[]),
  ('usr-admin', 'Fatou', 'Diarra', 'admin@bigfive.ci', null, null, 'admin-superieur', false, null, 'scrypt$16384$8$1$e486c0557a0da8463ebd7f3cbc8e4f83$54b5d095859db59145ebe4f2a80ac335d51adaea0e9b7203cfcbcfb3fe008d20a1ef8f278f555a095b83529a3169657878c3639639a162785b67f0673d360119', '{}'::section_admin[]),
  ('usr-editeur', 'Marc', 'Assi', 'editeur@bigfive.ci', null, null, 'admin-contenu', false, null, 'scrypt$16384$8$1$e34740232b28a7676399bb2d5946831d$1c0f08fdae6c17466551afcb52f5b83775180b912e175b20028b98d3758472a3b0703abb1eab08e73b676051b8a77ec7e06af2dff81bef753318d625529ff4ff', array['cms-site-vitrine', 'fiches-commerciales', 'modules-chapitres', 'formateurs', 'calendrier-sessions', 'coaching-prive', 'candidatures-formateurs', 'blog', 'referencement-contenu', 'historique-versions', 'statistiques-performance']::section_admin[]),
  ('usr-formateur', 'Coury', 'Othniel', 'formateur@bigfive.ci', null, null, 'formateur', false, 'for-othniel', 'scrypt$16384$8$1$b84ca1e1a26d95d8a61dc9c159b3f279$a50c771bf3bdeacb378ff814395346665cf5db175a0f365a74f04b4a8436d88f2c2ad2bb184e375fbad329a65e5b954f69352226d2fc39f80fafdfc6d3a3878a', '{}'::section_admin[]);

-- Personas apprenants transmis aux formateurs
insert into personas (utilisateur_id, age, secteur, experience, reseaux, objectif) values
  ('usr-aya', 27, 'Agence digitale', '1 à 3 ans', 'Instagram, TikTok', 'Signer 3 clients d’ici décembre'),
  ('usr-moussa', 34, 'Commerce de détail', '3 à 5 ans', 'WhatsApp, Facebook', 'Doubler les commandes entrantes');

-- Accès acquis
insert into acces (utilisateur_id, module_id, progression, achete_le, termine_le) values
  ('usr-aya', 'mod-fixer-le-juste-prix-de-ses-produits-et-services', 100, '2026-09-10', '2026-09-15'),
  ('usr-aya', 'mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 45, '2026-10-02', null);

-- Sessions de coaching collectif. `inscrits` porte les inscriptions de
-- démonstration, qui n’ont pas de ligne dans inscriptions_sessions.
insert into sessions_coaching (id, thematique_id, programme, formateur_id, date_seance, heure, duree_minutes, places, inscrits, presents, statut) values
  ('ses-001', 'th-ent-fondations', 'entrepreneurs', 'for-declercq', '2026-09-12', '18:00', 120, 25, 18, null, 'planifiee'),
  ('ses-002', 'th-sm-copywriting', 'social-media', 'for-othniel', '2026-09-19', '18:00', 120, 25, 19, null, 'planifiee'),
  ('ses-003', 'th-sm-fondations', 'social-media', 'for-waffo', '2026-10-03', '18:30', 120, 25, 7, null, 'planifiee');

-- Inscriptions détaillées, déduites des sujets soumis
alter table inscriptions_sessions disable trigger inscriptions_sessions_compteur;
insert into inscriptions_sessions (session_id, utilisateur_id, inscrit_le) values
  ('ses-002', 'usr-aya', '2026-09-05'),
  ('ses-002', 'usr-moussa', '2026-09-06');
alter table inscriptions_sessions enable trigger inscriptions_sessions_compteur;

-- Sujets soumis avant séance
insert into sujets_sessions (id, session_id, utilisateur_id, apprenant, preoccupation, attente, soumis_le) values
  ('suj-001', 'ses-002', 'usr-aya', 'Awa K.', 'Mes accroches sont vues mais ne génèrent presque aucun clic.', 'Une méthode pour tester plusieurs accroches rapidement.', '2026-09-05'),
  ('suj-002', 'ses-002', 'usr-moussa', 'Moussa D.', 'Adapter une même accroche à Instagram et LinkedIn sans la réécrire.', 'Des repères concrets par plateforme.', '2026-09-06');

-- Notes des apprenants
insert into notes_formateurs (id, formateur_id, utilisateur_id, origine, note, commentaire, date_note) values
  ('note-001', 'for-othniel', 'usr-moussa', 'collective', 5, 'Cas pratiques très concrets', '2026-08-12'),
  ('note-002', 'for-othniel', 'usr-fatou', 'privee', 4, 'J’aurais aimé plus de temps', '2026-07-28');

-- Articles du blog
insert into articles (id, slug, titre, chapo, contenu, auteur_id, categorie, image, image_alt, statut, publie_le, temps_lecture_minutes, a_la_une, seo_mot_cle_principal, seo_title, seo_meta_description, seo_og_title, seo_og_description, seo_og_image, seo_canonical, seo_indexable) values
  ('art-accroches', 'trois-secondes-pour-convaincre', 'Trois secondes pour convaincre : anatomie d’une accroche', 'Sur les formats courts, tout se joue avant la troisième seconde. Décomposition de ce qui retient réellement l’attention.', '## Ce que mesure la plateforme

La rétention initiale décide de la diffusion. Une vidéo excellente à partir de la dixième seconde ne sera jamais vue.

## Quatre accroches qui fonctionnent

1. La contradiction : annoncer l''inverse de ce qui est attendu.
2. Le chiffre précis : « 47 % des commerçants du marché… ».
3. La question fermée : elle force une réponse mentale.
4. Le geste : montrer avant de dire.

## Ce qui ne fonctionne plus

Le générique animé, la présentation de soi et le « bonjour tout le monde » coûtent les trois secondes qui comptent.', 'for-othniel', 'Social Média', '/images/blog/accroches.svg', 'Téléphone monté sur trépied filmant une intervenante', 'publie', '2026-07-28', 4, true, null, null, null, null, null, null, null, true),
  ('art-prix', 'pourquoi-vos-prix-sont-trop-bas', 'Pourquoi vos prix sont trop bas (et comment le vérifier en 20 minutes)', 'Sous-tarifer n’est presque jamais un choix stratégique : c’est un calcul qui n’a pas été fait. Voici comment le refaire.', '## Le symptôme

Vous travaillez beaucoup, votre chiffre d''affaires progresse, et pourtant la trésorerie ne suit pas. Dans neuf cas sur dix, le problème n''est pas le volume : c''est le prix unitaire.

## Le calcul que personne ne fait

Un prix juste couvre trois choses : les coûts directs de production, votre quote-part de coûts indirects, et votre rémunération. Retirez l''un des trois et vous vendez à perte sans le savoir.

### Les coûts directs

Listez tout ce qui disparaît quand la vente n''a pas lieu : matières, sous-traitance, transport.

### Les coûts indirects

Loyer, connexion, abonnements, amortissement du matériel. Divisez le total mensuel par le nombre d''unités vendues en moyenne.

### Votre rémunération

Fixez-la avant, pas après. C''est une charge, pas un reste.

## Et le marché ?

Le marché fixe une fourchette acceptable, pas votre prix. Si votre coût de revient sort de la fourchette, le problème est le modèle, pas le tarif.', 'for-declercq', 'Entrepreneuriat', '/images/blog/prix.svg', 'Calculatrice et carnet de comptes posés sur un bureau', 'publie', '2026-07-12', 6, false, null, null, null, null, null, null, null, true),
  ('art-whatsapp', 'whatsapp-business-le-canal-de-vente-le-plus-sous-estime', 'WhatsApp Business : le canal de vente le plus sous-estimé', 'La plupart des ventes se concluent déjà sur WhatsApp. Reste à arrêter de le faire au hasard.', '## Un canal déjà adopté

Vos clients y sont, vos concurrents aussi. Ce qui manque rarement, c''est l''audience ; c''est l''organisation.

## Trois réglages qui changent tout

1. Un catalogue à jour, avec des prix visibles.
2. Des réponses rapides pour les questions récurrentes.
3. Des étiquettes pour suivre l''état de chaque conversation.

## La relance

Une commande abandonnée se relance une fois, avec une information utile — jamais deux fois avec la même phrase.', 'for-soboro', 'Entrepreneuriat', '/images/blog/whatsapp.svg', 'Commerçante prenant une commande sur son téléphone', 'publie', '2026-06-30', 5, false, null, null, null, null, null, null, null, true),
  ('art-sessions', 'nouvelles-sessions-de-coaching-collectif', 'Nouvelles sessions de coaching collectif au calendrier', 'Trois sessions supplémentaires ouvrent ce trimestre, une par thématique, dans la limite de 25 places.', '## Ce qui change

Chaque thématique dispose désormais d''une session dédiée, animée par le formateur de la thématique.

## Comment y participer

L''accès à un module de la thématique ouvre l''accès à la session correspondante. La fiche apprenant doit être complétée avant de rejoindre la séance.', 'for-declercq', 'Actualités E-Masterclass Big Five', '/images/blog/sessions.svg', 'Session de coaching collectif en visioconférence', 'publie', '2026-06-15', 3, false, null, null, null, null, null, null, null, true),
  ('art-brouillon', 'choisir-son-reseau-social-principal', 'Choisir son réseau social principal', 'Article en cours de rédaction.', '## Brouillon

Contenu en préparation.', 'for-waffo', 'Social Média', '/images/blog/placeholder.svg', 'Illustration générique', 'brouillon', null, 3, false, null, null, null, null, null, null, null, false);

-- Modules mis en avant au bas des articles
insert into articles_modules (article_id, module_id) values
  ('art-accroches', 'mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting'),
  ('art-prix', 'mod-fixer-le-juste-prix-de-ses-produits-et-services'),
  ('art-whatsapp', 'mod-vendre-sans-site-web-whatsapp-business');

-- Transactions du prestataire de paiement
insert into transactions (reference, utilisateur_id, module_id, moyen, montant, statut, date_transaction, code_echec, detail_echec) values
  ('FP-2609-0412', 'usr-aya', 'mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 'Orange Money', 10000, 'reussie', '2026-09-26', null, null),
  ('FP-2609-0411', 'usr-moussa', 'mod-vendre-sans-site-web-whatsapp-business', 'Wave', 10000, 'reussie', '2026-09-26', null, null),
  ('FP-2609-0410', 'usr-fatou', 'mod-instagram-formats-et-croissance', 'Visa', 10000, 'echouee', '2026-09-25', 'carte-refusee', 'Carte refusée par la banque émettrice.'),
  ('FP-2509-0388', 'usr-aya', 'mod-fixer-le-juste-prix-de-ses-produits-et-services', 'Djamo', 10000, 'reussie', '2026-09-15', null, null);

-- Certificats déjà délivrés
insert into certificats (numero, utilisateur_id, module_id, prenom_nom, titre_module, programme, thematique, formateur, duree_minutes, date_realisation, date_delivrance, taux_completion) values
  ('EMBF-ENT-2026-000128', 'usr-aya', 'mod-fixer-le-juste-prix-de-ses-produits-et-services', 'Aya Koné', 'Fixer le juste prix de ses produits et services', 'Entrepreneurs', 'Fondations du business', 'Jérémie De Clercq', 60, '2026-09-15', '2026-09-15', 100);

-- Demandes de coaching privé
insert into demandes_coaching_prive (id, utilisateur_id, apprenant, module_id, formateur_id, besoins, disponibilites, creneaux, heures, statut, creneau, lien_session, recue_le) values
  ('dcp-001', 'usr-aya', 'Awa Koné', 'mod-accroches-qui-stoppent-le-scroll-et-ia-copywriting', 'for-othniel', 'Retravailler mes accroches pour un client dans la restauration, je n’arrive pas à dépasser 2 % d’engagement.', 'Soirs de semaine après 18 h, samedi matin.', '[{"date":"2026-10-06","debut":"18:30","fin":"20:30"},{"date":"2026-10-10","debut":"09:00","fin":"11:00"}]'::jsonb, 2, 'en-attente', null, null, '2026-09-24'),
  ('dcp-002', 'usr-moussa', 'Moussa Diabaté', 'mod-vendre-sans-site-web-whatsapp-business', 'for-soboro', 'Structurer mes relances WhatsApp après un premier échange.', 'Samedi matin.', '[{"date":"2026-09-12","debut":"10:00","fin":"12:00"}]'::jsonb, 2, 'payee', 'Samedi 12/09, 10h – 12h', 'https://zoom.us/j/00000000000', '2026-09-02'),
  ('dcp-003', 'usr-fatou', 'Fatou Bamba', 'mod-instagram-formats-et-croissance', 'for-waffo', 'Construire une présence Instagram pour ma marque de cosmétiques.', 'Mercredi après-midi.', '[{"date":"2026-09-30","debut":"14:00","fin":"15:00"}]'::jsonb, 1, 'confirmee-attente-paiement', null, null, '2026-09-18');

-- Suivi daté des demandes de coaching privé
insert into historique_coaching_prive (demande_id, statut, auteur, commentaire, cree_le) values
  ('dcp-001', 'en-attente', 'Awa Koné', null, '2026-09-24T10:12:00Z'),
  ('dcp-002', 'en-attente', 'Moussa Diabaté', null, '2026-09-02T08:30:00Z'),
  ('dcp-002', 'confirmee-attente-paiement', 'Équipe Big Five', 'Créneau retenu : samedi 12/09, 10h – 12h. Lien de paiement envoyé.', '2026-09-03T14:05:00Z'),
  ('dcp-002', 'payee', 'Équipe Big Five', null, '2026-09-04T09:40:00Z'),
  ('dcp-003', 'en-attente', 'Fatou Bamba', null, '2026-09-18T16:20:00Z'),
  ('dcp-003', 'confirmee-attente-paiement', 'Équipe Big Five', 'Créneau retenu : mercredi 30/09, 14h – 15h.', '2026-09-19T11:00:00Z');

-- Candidatures formateurs
insert into candidatures_formateurs (id, nom, expertise, message, whatsapp, email, lien, statut, recue_le) values
  ('cand-001', 'Éric N’Guessan', 'Publicité Meta Ads', '6 ans de gestion de campagnes pour des PME ivoiriennes, je veux enseigner la publicité payante aux SMM.', '+225 05 44 00 00 00', 'eric.nguessan@example.ci', 'https://www.linkedin.com/', 'nouvelle', '2026-09-20'),
  ('cand-002', 'Salimata Traoré', 'Branding & identité visuelle', 'Directrice artistique, je souhaite proposer un module sur l’identité de marque.', '+225 07 11 00 00 00', 'salimata.traore@example.ci', null, 'en-etude', '2026-09-12');

-- Journal d’administration
insert into journal (id, auteur, action, cible, date_entree) values
  ('j-001', 'Fatou Diarra', 'a publié le module', 'Accroches qui stoppent le scroll & IA copywriting', '2026-09-26T09:10:00Z'),
  ('j-002', 'Marc Assi', 'a modifié la fiche', 'Vendre sans site web : WhatsApp Business de A à Z', '2026-09-26T07:40:00Z'),
  ('j-003', 'Fatou Diarra', 'a attribué un accès gratuit', 'motif : lot concours', '2026-09-25T16:05:00Z');

-- Réglages financiers — ligne unique
insert into reglages_financiers (id, frais_paiement_pourcent, part_big_five_pourcent, part_formateur_pourcent, objectif_inscriptions_mensuel, objectif_ca_mensuel) values
  (true, 4, 70, 30, 450, 4500000);

-- Réglages SEO globaux — ligne unique
insert into reglages_seo (id, titre_par_defaut, gabarit_titre, description_par_defaut, image_sociale_par_defaut, google_search_console, ga4) values
  (true, 'E-Masterclass Big Five', '%s | E-Masterclass Big Five', 'Des modules de 60 minutes pour les professionnels du Social Media et les entrepreneurs d’Afrique francophone. 10 000 FCFA TTC par module, accès à vie.', '/images/og-default.svg', '', '');

-- Compteurs des identifiants applicatifs
select setval('seq_session_coaching', 3, true);
select setval('seq_sujet_session', 2, true);
select setval('seq_note_formateur', 2, true);
select setval('seq_entree_journal', 3, true);
select setval('seq_demande_coaching_prive', 3, true);
select setval('seq_candidature_formateur', 2, true);
select setval('seq_certificat', 128, true);